version: '2'
services:
  cadena-database:
    image: neo4j:3.0.7
    environment:
      NEO4J_AUTH: none
    ports:
      - "7473:7473"
      - "7474:7474"
    volumes:
      - cadena:/data
    networks:
      - cadena
  cadena-application:
    image: registry.neec.xyz/dev/cadena-application:latest
    environment:
      CADENA_PORT: 3000
      CADENA_DATABASE_URL: http://cadena-database:7474
      CADENA_SECRET_KEY_BASE: x
      CUENTA_URL: http://cuenta-application:4000/
      CAJA_URL: http://caja-application:9000/
      IMAGEN_URL: http://imagen-application:8000/
      STATIC_URL: http://localhost
      RAILS_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - cadena-database
    networks:
      - cadena
      - cadena-cuenta
      - cadena-imagen
      - caja-cadena

volumes:
  cadena:
    driver: local

networks:
  cadena:
    driver: bridge
  cadena-cuenta:
    external:
      name: neeco_cadena-cuenta
  cadena-imagen:
    external:
      name: neeco_cadena-imagen
  caja-cadena:
    external:
      name: neeco_caja-cadena
