version: '2'
services:
  cadena-database:
    image: neo4j:3.0.7
    environment:
      NEO4J_AUTH: none
    ports:
      - "7473:7473"
      - "7474:7474"
    volumes:
      - cadena:/data
    networks:
      - cadena
  cadena-application:
    image: registry.neec.xyz/neeco/cadena-application:latest
    environment:
      CADENA_PORT: 3000
      CADENA_DATABASE_URL: http://cadena-database:7474
      CADENA_SECRET_KEY_BASE: 1f0bef8714009078799cf781b489f5012c625a12dc4478388634af4b784b72c5bd1e3f2630a361af351cfaf5bf84559f818b2796b9fcbc331cfa404a3805cb6f
      CADENA_CUENTA_URL: http://cuenta-application:4000/
      CADENA_CAJA_URL: http://caja-application:9000/
    ports:
      - "3000:3000"
    depends_on:
      - cadena-database
    networks:
      - cadena
      - cadena-cuenta
      - cadena-caja

volumes:
  cadena:
    external:
      name: neeco_cadena

networks:
  cadena:
    external:
      name: neeco_cadena
  cadena-cuenta:
    external:
      name: neeco_cadena-cuenta
  cadena-caja:
    external:
      name: neeco_cadena-caja
