version: '2'
services:
  cadena-database:
    image: neo4j:3.0.7
    environment:
      NEO4J_AUTH: none
    ports:
      - "7473:7473"
      - "7474:7474"
    volumes:
      - cadena:/data
    networks:
      - neeco
  cadena-application:
    image: registry.neec.xyz/dev/cadena-application:latest
    environment:
      CADENA_PORT: 3000
      CADENA_DATABASE_URL: http://cadena-database:7474
      CADENA_SECRET_KEY_BASE: x
      CUENTA_URL: http://cuenta-application:4000/
      CAJA_URL: http://caja-application:9000/
      IMAGEN_URL: http://imagen-application:8000/
      STATIC_IMAGE_URL: http://localhost/images/
      RAILS_ENV: development
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - cadena-database
    networks:
      - neeco

volumes:
  cadena:
    driver: local

networks:
  neeco:
    external:
      name: neeco_develop
